import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://buggy.justtestit.org/');
  await page.getByRole('link', { name: 'Register' }).click();
  await page.getByLabel('Login').click();
  await page.getByLabel('Login').fill('Kyaraluna011');
  await page.getByLabel('First Name').click();
  await page.getByLabel('First Name').fill('David Alessandro');
  await page.getByLabel('First Name').press('Tab');
  await page.getByLabel('Last Name').fill('Baron Garcia');
  await page.getByLabel('Last Name').press('Tab');
  await page.getByLabel('Password', { exact: true }).fill('Qa230423.');
  await page.getByLabel('Password', { exact: true }).press('Tab');
  await page.getByLabel('Confirm Password').fill('Qa230423.');
  await page.getByRole('button', { name: 'Register' }).click();
  await page.getByText('Registration is successful').click();
  await page.getByPlaceholder('Login').click();
  await page.getByPlaceholder('Login').fill('Kyaraluna011');
  await page.getByRole('navigation').locator('input[name="password"]').click();
  await page.getByRole('navigation').locator('input[name="password"]').fill('Qa230423.');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Profile' }).click();
  await page.getByLabel('Gender').click();
  await page.getByLabel('Gender').fill('Male');
  await page.getByLabel('Age', { exact: true }).click();
  await page.getByLabel('Age', { exact: true }).fill('33');
  await page.getByLabel('Address').click();
  await page.getByLabel('Address').fill('Calle 19 # 03 - 70 casa 19');
  await page.getByLabel('Phone').click();
  await page.getByLabel('Phone').fill('3115153366');
  await page.getByRole('combobox', { name: 'Hobby' }).selectOption('Video Games');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByText('The profile has been saved successful').first().click();
  await page.getByText('Hi, David Alessandro').click();
  await page.getByRole('link', { name: 'Buggy Rating' }).click();
  await page.getByRole('link', { name: 'Guilia Quadrifoglio' }).click();
  await page.getByLabel('Your Comment (optional)').click();
  await page.getByLabel('Your Comment (optional)').fill('El carro de color rojo es genial');
  await page.getByRole('button', { name: 'Vote!' }).click();
  await page.getByText('Thank you for your vote!').click();
});